systemLog:
  destination: file
  path: "/var/log/mongodb/membermelon.log"
  logAppend: true
storage:
  engine: wiredTiger
  dbPath: "/data/membermelon"
  journal:
    enabled: true
processManagement:
  fork: true
net:
  bindIp: 127.0.0.1,127.0.1.1
  port: 13666
replication:
  replSetName: 'membermelon'
